name: Trivy Scan

on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: write
  actions: read
  security-events: write

jobs:
  build-and-push:
    name: 🔨 개발환경 Spring Boot CI[Build & Push]
    permissions:
      contents: write
      id-token: write
    uses: BG011715-K-O-L/ops-template/.github/workflows/spring-boot-ci.yml@main
    with:
      source_repository: kol-itg-gw
      ops_repository: kol-ops
      environment: dev
      ref: main
    secrets:
      ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}

  run-trivy:
    needs: build-and-push
    uses: ktdev-templates/Trivy_Template/.github/workflows/trivy-container.yaml@main
    with:
      image: "${{ needs.build-and-push.outputs.IMAGE_NAME }}"
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    permissions:
      id-token: write
      contents: read
      actions: read
      security-events: write
